const dictionary = {
  en: {
    brandName: "Datalloy.ai",
    footerBrand: "Datalloy.ai",
    navSolution: "Solution",
    navCapabilities: "Capabilities",
    navIndustries: "Industries",
    navTeam: "Team",
    navCta: "Request Demo",
    eyebrow: "AI-Native Synthetic Data Platform",
    heroTitle: "Generate production-ready raw data on demand.",
    heroSubtitle:
      "Datalloy.ai generates high-fidelity, protocol-compliant raw operational data for training, testing, and compliance. We do not just mimic summary statistics; we generate complete raw records directly usable by standard tools.",
    heroTarget: "Built for ML, data, and security teams in regulated industries.",
    heroPrimary: "Get a private pilot",
    heroSecondary: "See how it works",
    heroProof:
      "Core results appear at top venues including USENIX Security, NSDI, and SIGMETRICS, with additional publications at NDSS, CoNEXT, and UbiComp.",
    panelTitle: "Datalloy Core Engine",
    panelBody:
      "Generate tabular data, time-series, system logs, and network traffic as complete raw datasets with controllable attributes and rare-case steering.",
    panelMetricValue1: "Raw-data native",
    panelMetric1: "Tool-ready outputs",
    panelMetricValue2: "Attribute-controlled",
    panelMetric2: "Field-level scenario control",
    panelMetricValue3: "Rare-case rich",
    panelMetric3: "Statistical edge coverage",
    solutionTitle: "Win the data bottleneck. Launch models with confidence.",
    solutionBody:
      "Your teams cannot wait months for scarce or regulated datasets. Datalloy.ai generates protocol-compliant full raw data, not feature-only statistics, so you can validate, harden, and ship faster.",
    value1: "Generate complete raw datasets across tabular, time-series, logs, and traffic.",
    value2: "Protocol-compliant outputs that plug into SIEM, IDS, ETL, and ML tools.",
    value3: "Control attributes on demand and synthesize statistically rare edge cases.",
    pillar1Title: "Break data silos",
    pillar1Body: "Share model-ready data across teams without exposing sensitive records.",
    pillar2Title: "Unlock rare events",
    pillar2Body: "Generate corner cases on demand to harden mission-critical AI.",
    pillar3Title: "Cut storage costs",
    pillar3Body: "Store lightweight generative models, replay any historical scenario instantly.",
    capabilitiesTitle: "One platform for multimodal operational data.",
    capabilitiesBody: "Cover tabular, time-series, system logs, and network traffic with full-fidelity raw outputs.",
    deploymentTitle: "Deploy fast, stay compliant.",
    deploymentBody: "Choose SaaS, VPC, or on-prem. Keep data behind your firewall.",
    deploy1Title: "Flexible deployment",
    deploy1Body: "SaaS, VPC, or on-prem with isolated pipelines.",
    deploy2Title: "Rapid onboarding",
    deploy2Body: "Map schemas/protocols and deliver a pilot in weeks, not quarters.",
    deploy3Title: "Seamless integration",
    deploy3Body: "Outputs in PCAP, CSV, Parquet, JSONL; plug into IDS, SIEM, data, and ML stacks.",
    cap1Title: "Network traffic (protocol-true PCAP)",
    cap1Body: "Generate full packet-level raw traffic directly ingestible by IDS, SIEM, and traffic analyzers.",
    cap2Title: "Multimodal time-series data",
    cap2Body: "Correlated telemetry and sensor sequences with controllable long-range dependencies.",
    cap3Title: "System logs & traces",
    cap3Body: "Raw structured and semi-structured logs ready for anomaly detection and root-cause workflows.",
    cap4Title: "Tabular at scale",
    cap4Body: "High-coverage raw tabular records for risk, compliance, and forecasting pipelines.",
    industriesTitle: "Built for regulated, revenue-critical industries",
    industriesBody: "Where real-world data is scarce, sensitive, or too risky to capture.",
    industryAxisX: "Data sensitivity",
    industryAxisY: "Operational risk",
    industry1Title: "Autonomous & connected vehicles",
    industry1Body: "Simulate extreme driving conditions and sensor failures safely.",
    industry1Scenario: "Scenario: Rainy-night sensor dropout.",
    industry2Title: "Cybersecurity & cloud",
    industry2Body: "Train detectors on realistic attack traffic without exposing users.",
    industry2Scenario: "Scenario: Lateral movement attack replay.",
    industry3Title: "IoT & smart manufacturing",
    industry3Body: "Model equipment degradation and rare failures before they occur.",
    industry3Scenario: "Scenario: Motor overheating before failure.",
    industry4Title: "Finance & compliance",
    industry4Body: "Generate risk scenarios while preserving data privacy.",
    industry4Scenario: "Scenario: Portfolio stress-test shock.",
    comparisonTitle: "Compare your options",
    comparisonBody: "Not just statistical features: generate complete raw data with protocol fidelity and tool compatibility.",
    comparisonHeadSynth: "Datalloy.ai",
    comparisonHeadAnon: "Anonymized data",
    comparisonHeadEncrypted: "Encrypted data",
    comparisonHeadLlm: "General-purpose LLMs",
    comparisonRow1: "Raw data completeness",
    comparisonRow1Synth: "Full records",
    comparisonRow1Anon: "Low",
    comparisonRow1Encrypted: "Partial",
    comparisonRow1Llm: "Partial",
    comparisonRow2: "Rare-event control",
    comparisonRow2Synth: "High",
    comparisonRow2Anon: "Low",
    comparisonRow2Encrypted: "Low",
    comparisonRow2Llm: "Medium",
    comparisonRow3: "Compliance risk",
    comparisonRow3Synth: "Low",
    comparisonRow3Anon: "Medium",
    comparisonRow3Encrypted: "Low",
    comparisonRow3Llm: "High",
    comparisonRow4: "Usable directly in standard tools",
    comparisonRow4Synth: "Yes",
    comparisonRow4Anon: "Yes",
    comparisonRow4Encrypted: "Partial",
    comparisonRow4Llm: "Partial",
    comparisonRow5: "Cost",
    comparisonRow5Synth: "Low",
    comparisonRow5Anon: "Medium",
    comparisonRow5Encrypted: "High",
    comparisonRow5Llm: "High",
    comparisonNote: "Assessment reflects typical enterprise deployments.",
    timelineTitle: "Why teams choose Datalloy.ai",
    timelineBody: "We build domain-specific raw-data generation systems, not generic feature-only simulators.",
    timeline1Title: "Model schema + protocol constraints",
    timeline1Body: "Encode schema, protocol, and system constraints directly into the generation pipeline.",
    timeline2Title: "Synthesize at scale",
    timeline2Body: "Generate massive raw data volumes, including statistically rare edge cases.",
    timeline3Title: "Validate with clients",
    timeline3Body: "Partner with early adopters to benchmark real-world effectiveness.",
    teamTitle: "Research-grade team, product-grade delivery",
    teamBody:
      "<a href='https://www.shinan.info' target='_blank' rel='noopener noreferrer'>Shinan Liu</a> is a tenure-track Assistant Professor and PhD advisor in the Department of Data and Systems Engineering at The University of Hong Kong, and leads the <a href='https://naisslab.github.io' target='_blank' rel='noopener noreferrer'>Networked AI Systems and Security (NAISS) Lab</a>.",
    founderName: "Shinan Liu",
    founderTitle: "Tenure-track Assistant Professor & PhD Advisor, HKU DSE",
    founderBody:
      "PhD in Computer Science from the University of Chicago (advised by Nick Feamster). His research builds usable, reliable, high-performance ML systems for network analytics and security/privacy. Core results appear at top venues including USENIX Security, NSDI, SIGMETRICS, NDSS, CoNEXT, and UbiComp.",
    teamFocusTitle: "Core expertise & honors",
    teamFocusBody:
      "Core strengths span multimodal operational data modeling, cybersecurity, and production-grade generative systems across tabular, time-series, logs, and traffic with protocol fidelity and tool-ready integration. Recipient of Rising Star in ML & Systems, CBI Fellowship, ACTION AI Fellowship, and Daniels Fellowship. Research has been featured by Forbes, The Wall Street Journal, and ACM TechNews.",
    teamProgressTitle: "Go-to-market",
    teamProgressBody:
      "Pilot programs are underway with telecom, security, and automotive partners, covering protocol mapping, scenario design, data validation, and model evaluation to accelerate production deployment. We work jointly with customer teams from PoC definition to integration into existing SIEM/IDS/ML workflows, with clear milestones on quality, compliance, and deployment readiness. Previous projects have been deployed at organizations including Verizon and NetMicroscope.",
    contactTitle: "Start with your rarest data problems.",
    contactBody:
      "We are onboarding pilot partners in cybersecurity, autonomous systems, and IoT. Share your use case across tabular, time-series, logs, or traffic data and we will design a synthetic data plan in days, not quarters.",
    contactButton: "Request demo",
    contactNote: "We respond within 48 hours. NDA-ready.",
    footerTag: "High-fidelity synthetic data infrastructure for operational systems",
    footerCity: "Hong Kong",
    footerContact: "shinan6@hku.hk",
    contactName: "Name",
    contactEmail: "Work email",
    contactCompany: "Company",
    contactMessage: "Tell us about your data needs"
  },
  zh: {
    brandName: "数据合金",
    footerBrand: "数据合金",
    navSolution: "解决方案",
    navCapabilities: "能力",
    navIndustries: "行业",
    navTeam: "团队",
    navCta: "预约演示",
    eyebrow: "AI驱动的高保真合成数据平台",
    heroTitle: "按需生成开箱即用的生产级数据",
    heroSubtitle:
      "数据合金（Datalloy.ai）生成高保真、协议合规的原始运营数据，用于训练、测试与合规验证。我们不只拟合统计特征，而是输出可被标准工具直接使用的完整原始记录。",
    heroTarget: "面向高合规行业的机器学习、数据与安全团队。",
    heroPrimary: "申请私有试点",
    heroSecondary: "了解工作原理",
    heroProof: "核心成果发表于USENIX Security、NSDI、SIGMETRICS等顶会，并扩展至NDSS、CoNEXT、UbiComp，持续聚焦网络数据分析与安全隐私中的机器学习系统。",
    panelTitle: "Datalloy Core Engine",
    panelBody: "统一生成表格、时序、系统日志与网络流量等多类运营数据，支持属性按需控制与统计稀有边缘案例合成。",
    panelMetricValue1: "原始数据级",
    panelMetric1: "标准工具可直接使用",
    panelMetricValue2: "属性可控",
    panelMetric2: "字段级场景控制",
    panelMetricValue3: "稀有案例增强",
    panelMetric3: "覆盖统计长尾",
    solutionTitle: "打破数据瓶颈，加速模型落地。",
    solutionBody:
      "关键行业的数据往往最稀缺、最敏感。数据合金按需生成协议合规的完整原始数据，而非只合成统计特征，让验证、加固与上线速度领先竞争对手。",
    value1: "覆盖表格、时序、系统日志、网络流量的完整原始数据。",
    value2: "协议合规输出，可直接接入IDS、SIEM、ETL与ML工具链。",
    value3: "按需控制属性，批量生成统计稀有的边缘案例。",
    pillar1Title: "打破数据孤岛",
    pillar1Body: "在不泄露敏感信息的情况下实现跨团队协作训练。",
    pillar2Title: "生成稀有事件",
    pillar2Body: "按需生成边缘案例，提升关键模型的鲁棒性。",
    pillar3Title: "降低数据成本",
    pillar3Body: "存储轻量模型，随时回放历史场景。",
    capabilitiesTitle: "一套平台覆盖多类运营数据",
    capabilitiesBody: "统一覆盖表格、时序、系统日志、网络流量，并输出高保真原始数据。",
    deploymentTitle: "快速部署，合规上线。",
    deploymentBody: "支持SaaS、VPC或本地部署，数据不出内网。",
    deploy1Title: "灵活部署",
    deploy1Body: "SaaS、VPC或本地部署，隔离式流程。",
    deploy2Title: "快速上手",
    deploy2Body: "快速完成模式/协议映射与试点交付，以周计而非季度。",
    deploy3Title: "无缝集成",
    deploy3Body: "支持PCAP、CSV、Parquet、JSONL，直连IDS、SIEM、数据与ML流程。",
    cap1Title: "网络流量（协议级PCAP）",
    cap1Body: "生成完整包级原始流量，可直接用于IDS、SIEM和流量分析工具。",
    cap2Title: "多模态时序数据",
    cap2Body: "生成具有关联关系的遥测与传感器序列，支持长程依赖控制。",
    cap3Title: "系统日志与追踪",
    cap3Body: "生成结构化与半结构化原始日志，用于异常检测与根因分析流程。",
    cap4Title: "高覆盖表格数据",
    cap4Body: "生成用于风险、合规与预测流程的高覆盖原始表格记录。",
    industriesTitle: "面向高合规、营收关键行业",
    industriesBody: "真实数据稀缺、敏感或获取成本极高的场景。",
    industryAxisX: "数据敏感度",
    industryAxisY: "业务风险",
    industry1Title: "自动驾驶与车联网",
    industry1Body: "安全模拟极端路况与传感器失效。",
    industry1Scenario: "场景：雨夜传感器失效。",
    industry2Title: "网络安全与云计算",
    industry2Body: "生成真实攻击流量，避免暴露用户数据。",
    industry2Scenario: "场景：横向移动攻击回放。",
    industry3Title: "物联网与智能制造",
    industry3Body: "提前建模设备衰退与罕见故障。",
    industry3Scenario: "场景：电机过热至故障前兆。",
    industry4Title: "金融与合规",
    industry4Body: "在保护隐私的前提下生成风险场景。",
    industry4Scenario: "场景：压力测试与极端冲击。",
    comparisonTitle: "方案对比",
    comparisonBody: "不止统计特征拟合，而是协议级保真、标准工具可直用的完整原始数据。",
    comparisonHeadSynth: "数据合金",
    comparisonHeadAnon: "脱敏数据",
    comparisonHeadEncrypted: "加密数据",
    comparisonHeadLlm: "通用大模型（LLM）",
    comparisonRow1: "原始数据完整性",
    comparisonRow1Synth: "完整记录",
    comparisonRow1Anon: "低",
    comparisonRow1Encrypted: "部分",
    comparisonRow1Llm: "部分",
    comparisonRow2: "稀有事件可控性",
    comparisonRow2Synth: "高",
    comparisonRow2Anon: "低",
    comparisonRow2Encrypted: "低",
    comparisonRow2Llm: "中",
    comparisonRow3: "合规风险",
    comparisonRow3Synth: "低",
    comparisonRow3Anon: "中",
    comparisonRow3Encrypted: "低",
    comparisonRow3Llm: "高",
    comparisonRow4: "标准工具直接可用",
    comparisonRow4Synth: "是",
    comparisonRow4Anon: "是",
    comparisonRow4Encrypted: "部分",
    comparisonRow4Llm: "部分",
    comparisonRow5: "成本",
    comparisonRow5Synth: "低",
    comparisonRow5Anon: "中",
    comparisonRow5Encrypted: "高",
    comparisonRow5Llm: "高",
    comparisonNote: "评估基于典型企业部署场景。",
    timelineTitle: "为什么团队选择Datalloy.ai",
    timelineBody: "我们构建的是领域专用的原始数据生成系统，而非只做特征拟合的通用造数工具。",
    timeline1Title: "建模模式与协议约束",
    timeline1Body: "将模式、协议与系统约束直接融入生成流程。",
    timeline2Title: "规模化合成",
    timeline2Body: "高效生成海量原始数据并覆盖统计稀有边缘事件。",
    timeline3Title: "客户共创验证",
    timeline3Body: "与早期伙伴联合评测真实效果。",
    teamTitle: "学术级研究团队，产品级交付能力",
    teamBody: "<a href='https://www.shinan.info' target='_blank' rel='noopener noreferrer'>刘诗楠</a>现任香港大学数据与系统工程系长聘轨助理教授、博士生导师，领导<a href='https://naisslab.github.io' target='_blank' rel='noopener noreferrer'>网络智能系统与安全（NAISS）实验室</a>。",
    founderName: "刘诗楠",
    founderTitle: "香港大学数据与系统工程系 长聘轨助理教授、博士生导师",
    founderBody: "芝加哥大学计算机科学博士（师从Nick Feamster），研究聚焦网络数据分析与安全隐私中的机器学习系统，强调易用、可靠与高性能。核心成果发表于USENIX Security、NSDI、SIGMETRICS等顶会，并扩展至NDSS、CoNEXT、UbiComp。",
    teamFocusTitle: "核心能力与荣誉",
    teamFocusBody: "聚焦多模态运营数据建模、网络安全与生成系统工程化，覆盖表格、时序、系统日志与网络流量，强调协议一致性、可解释控制与标准工具可集成。获机器学习与系统领域新星奖、CBI奖学金、ACTION人工智能奖学金、Daniels奖学金，研究成果被福布斯、华尔街日报与ACM TechNews报道。",
    teamProgressTitle: "商业化推进",
    teamProgressBody: "正与电信、安全、汽车伙伴推进试点，围绕真实业务场景开展协议映射、场景设计、数据验证与模型评测，持续打磨从PoC到规模化部署的交付流程。我们与客户团队联合推进，从试点定义到接入既有SIEM、IDS与机器学习工作流，按阶段完成质量、合规与上线准备目标。此前的项目在Verizon、NetMicroscope等公司均有部署。",
    contactTitle: "从最稀缺的数据问题开始。",
    contactBody: "我们正在招募网络安全、自动驾驶与IoT的试点合作伙伴，覆盖表格、时序、系统日志与网络流量数据场景，快速交付可落地方案。",
    contactButton: "预约演示",
    contactNote: "48小时内回复，可签署NDA。",
    footerTag: "面向运营系统的高保真合成数据基础设施",
    footerCity: "中国香港",
    footerContact: "shinan6@hku.hk",
    contactName: "姓名",
    contactEmail: "工作邮箱",
    contactCompany: "公司",
    contactMessage: "描述你的数据需求"
  }
};

const langButtons = document.querySelectorAll(".lang-btn");
const i18nNodes = document.querySelectorAll("[data-i18n]");
const i18nHtmlNodes = document.querySelectorAll("[data-i18n-html]");
const i18nPlaceholders = document.querySelectorAll("[data-i18n-placeholder]");

function setLanguage(lang) {
  const strings = dictionary[lang];
  if (!strings) return;

  i18nNodes.forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (strings[key]) node.textContent = strings[key];
  });

  i18nHtmlNodes.forEach((node) => {
    const key = node.getAttribute("data-i18n-html");
    if (strings[key]) node.innerHTML = strings[key];
  });

  i18nPlaceholders.forEach((node) => {
    const key = node.getAttribute("data-i18n-placeholder");
    if (strings[key]) node.setAttribute("placeholder", strings[key]);
  });

  langButtons.forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });

  document.documentElement.lang = lang === "zh" ? "zh-Hans" : "en";
}

langButtons.forEach((btn) => {
  btn.addEventListener("click", () => setLanguage(btn.dataset.lang));
});

setLanguage("zh");
